export enum OrderStatus {
    PENDING = "PENDING",
    PAID = "PAID",
    PROCESSING = "PROCESSING",
    READY_FOR_PICKUP = "READY_FOR_PICKUP",
    SHIPPED = "SHIPPED",
    ON_DELIVERY = "ON_DELIVERY",
    DELIVERED = "DELIVERED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED"
}